package com.xfboy.drl.login;

import com.xfboy.login.Vip;
import org.drools.core.util.StringUtils
import java.io.Console
import java.util.Scanner;
import com.xfboy.login.LoginServiceImpl;

rule "初次登陆"
    salience 100
    when
        $vip:Vip(StringUtils.isEmpty(name)&&StringUtils.isEmpty(password));
    then
        String tempName;
        String tempPassword;
        Console console=System.console();
        Scanner scanner=new Scanner(System.in);
        System.out.println("请输入用户名:");
        tempName=(console!=null?console.readLine():scanner.nextLine());
        System.out.println("请输入密码:");
        tempPassword=(console!=null?new String(console.readPassword()):scanner.nextLine());
        $vip.setName(tempName.trim());
        $vip.setPassword(tempPassword.trim());

        update($vip);
end

rule "没有输入用户名"
    salience 90
    when
        $vip:Vip(!StringUtils.isEmpty(password)&&StringUtils.isEmpty(name));
    then
        String tempName;
        Console console=System.console();
        Scanner scanner=new Scanner(System.in);
        System.out.println("请输入用户名：");
        tempName=(console!=null?console.readLine():scanner.nextLine());
        $vip.setName(tempName);

        update($vip);
end

rule "没有输入密码"
    salience 90
    when
        $vip:Vip(!StringUtils.isEmpty(name)&&StringUtils.isEmpty(password));
    then
        String tempPassword;
        Console console=System.console();
        Scanner scanner=new Scanner(System.in);
        System.out.println("请输入密码：");
        tempPassword=(console!=null?new String(console.readPassword()):scanner.nextLine());
        $vip.setPassword(tempPassword.trim());

        update($vip);
end

rule "输入正确的用户名和密码"
    salience 80
    when
    $vip:Vip(!StringUtils.isEmpty(name)&&!StringUtils.isEmpty(password),LoginServiceImpl.checkDB(name,password));
    then
    System.out.println("欢迎!!"+$vip.getName());

end

rule "输入错误的用户名和密码"
    salience 80
    when
    $vip:Vip(!StringUtils.isEmpty(name)&&!StringUtils.isEmpty(password),!LoginServiceImpl.checkDB(name,password));
    then
    System.out.println("用户名或密码错误");
    $vip.setName("");
    $vip.setPassword("");
    update($vip);

end
